services:
  db:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - ${EMAIL_SERVER_PORT}:1025
      - ${EMAIL_SERVER_HTTP_PORT}:8025
